AppName="PanDocElectron"
vReleasDir="releases/"
vVersion="-v1"
vArchOld="x64"
vArchNew="64Bit"
vOSOld="darwin"
vOSNew="MacOSX"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
vOSOld="win32"
vOSNew="win32"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
vOSOld="linux"
vOSNew="linux"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"

vArchOld="ia32"
vArchNew="32Bit"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
vOSOld="win32"
vOSNew="win32"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
vOSOld="linux"
vOSNew="linux"
mv "${vReleasDir}${AppName}-${vOSOld}-${vArchOld}" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
zip -r "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}.zip" "${vReleasDir}${AppName}-${vOSNew}-${vArchNew}${vVersion}"
